id: I5B6D17E6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T04:04:12+00:00'
last_modified: '2022-06-07T17:45:29.719471+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC235
  title: 'མཚོ་བོད་ས་མཐོའི་རྒྱུན་མཐོང་སྔོ་སྨན། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    55FC:
      image_group_id: I2PD18130
      title: ''
      total_pages: 904
      order: 1
      base_file: 55FC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
