id: P003124
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 10:41:54.881579
source_metadata:
  id: bdr:W1AC235
  title: 'མཚོ་བོད་ས་མཐོའི་རྒྱུན་མཐོང་སྔོ་སྨན། '
  author: ''
  volumes:
    99cee55c599745cc8b0397aa9d200b54:
      image_group_id: I2PD18130
      title: ''
      volume_number: 1
      total_pages: 904
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
